import gzip
from pathlib import Path

try:
    Import("env")  # noqa: F821 — provided by PlatformIO/SCons
    ROOT = Path(env["PROJECT_DIR"])  # noqa: F821
except NameError:
    ROOT = Path(__file__).resolve().parents[1]

WEB = ROOT / "assets" / "web"
OUT = ROOT / "include" / "web_assets.h"

FILES = [
    ("INDEX_HTML", "index.html", "text/html"),
    ("APP_CSS", "app.css", "text/css"),
    ("APP_JS", "app.js", "application/javascript"),
]


def to_c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}_GZ[] PROGMEM = {{"]
    chunk = []
    for b in data:
        chunk.append(f"0x{b:02x}")
        if len(chunk) == 16:
            lines.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append(f"static const size_t {name}_GZ_LEN = {len(data)};")
    return "\n".join(lines)


def embed() -> None:
    parts = [
        "#pragma once",
        "#include <Arduino.h>",
        "// Auto-generated by scripts/embed_assets.py — do not edit.",
        "",
    ]
    for sym, filename, mime in FILES:
        path = WEB / filename
        raw = path.read_bytes()
        gz = gzip.compress(raw, compresslevel=9)
        parts.append(f"// {filename} raw={len(raw)} gzip={len(gz)} type={mime}")
        parts.append(to_c_array(sym, gz))
        parts.append(f'static const char {sym}_MIME[] = "{mime}";')
        parts.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"[embed_assets] Wrote {OUT} ({OUT.stat().st_size} bytes)")


embed()
