#pragma once

#define NANOEXTEND_VERSION_MAJOR 1
#define NANOEXTEND_VERSION_MINOR 0
#define NANOEXTEND_VERSION_PATCH 3

#ifndef NANOEXTEND_FW_VERSION
#define NANOEXTEND_FW_VERSION "1.0.3"
#endif

#define NANOEXTEND_API_VERSION "v1"
#define NANOEXTEND_PLATFORM_PIN "pioarduino-55.03.39"
#define NANOEXTEND_ARDUINO_CORE_TARGET "3.3.9"
#define NANOEXTEND_IDF_TARGET "5.5.4"
